# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  test:
    steps:
      - checkout
      - run: mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/testng/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/testng/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/testng
      - store_artifacts:
          path: target/jacoco-reports
          destination: Coverage report

    docker:
      - image: circleci/openjdk:8u171-jdk
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - test